import NavBar from "./components/NavBar";
import "./globals.css";

export const metadata = {
  title: "Pokémon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" dark:bg-gray-800 bg-slate-300">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
